name: YouTube Download Bot

on:
  workflow_dispatch:  # ุนูุดุงู ุชูุฏุฑ ุชุดุบูู ูุฏูู
  schedule:
    - cron: '0 0 * * *'  # ูุดุบู ุชููุงุฆู ูู ููู (ุงุฎุชูุงุฑู)

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # ุนุดุงู ูุง ูุนูู ููุฃุจุฏ
    
    steps:
    # 1. ุฌูุจ ุงูููุฏ
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. ุฅุนุฏุงุฏ ุจุงูุซูู
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    # 3. ุชุซุจูุช ุงูููุชุจุงุช
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install yt-dlp==2023.11.16  # ูุณุฎุฉ ูุณุชูุฑุฉ
        pip install python-telegram-bot==20.7
        pip install requests

    # 4. ุฅูุดุงุก ูุฌูุฏ ุงูุชุญูููุงุช
    - name: Create downloads directory
      run: |
        mkdir -p downloads
        chmod 777 downloads/

    # 5. ุฅูุดุงุก ููู ุงูููููุฒ ูู GitHub Secrets
    - name: Create cookies file
      run: |
        # ุฃูุดุฆ ููู ุงูููููุฒ ูู ุงูุณุฑ
        echo '${{ secrets.YOUTUBE_COOKIES }}' > cookies.txt
        
        # ุชุญูู ูู ุฃู ุงูููู ูุด ูุงุฑุบ
        if [ -s "cookies.txt" ]; then
          echo "โ ุชู ุฅูุดุงุก ููู ุงูููููุฒ ุจูุฌุงุญ"
          echo "ุนุฏุฏ ุงูุฃุณุทุฑ: $(wc -l < cookies.txt)"
          # ุนุฑุถ ุฃูู ุณุทุฑ ููุชุญูู
          head -1 cookies.txt
        else
          echo "โ ููู ุงูููููุฒ ูุงุฑุบ! ุณูุชู ุงูุนูู ุจุฏููู"
          touch cookies.txt
        fi
        
        chmod 644 cookies.txt

    # 6. ุชุดุบูู ุงูุจูุช
    - name: Run the bot
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      run: |
        echo "๐ ุจุฏุก ุชุดุบูู ุงูุจูุช..."
        python bot.py

    # 7. ุชูุธูู ุงููููุงุช (ุงุฎุชูุงุฑู)
    - name: Cleanup
      if: always()
      run: |
        echo "๐งน ุชูุธูู ุงููููุงุช ุงููุคูุชุฉ..."
        rm -f cookies.txt
        rm -rf downloads/*
