name: Run Telegram Bot

on:
  workflow_dispatch:   # تشغيل يدوي
  push:                # يشتغل عند أي دفع للكود
  schedule:            # يعيد تشغيله كل ساعة
    - cron: "0 * * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install ffmpeg
      run: sudo apt-get update && sudo apt-get install -y ffmpeg

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install -U yt-dlp   # تحديث yt-dlp دائماً

    - name: Run bot
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      run: |
        python bot.py
