name: Run YouTube Download Bot
on:
  workflow_dispatch:  # ูุณูุญ ุจุชุดุบูู Workflow ูุฏููุงู
  schedule:
    - cron: '0 0 * * *'  # ูุดุบู ุชููุงุฆูุงู ูู ููู ูู ููุชุตู ุงูููู (ุงุฎุชูุงุฑู)

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
    # 1. Checkout ุงูููุฏ
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. ุฅุนุฏุงุฏ Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    # 3. ุชุซุจูุช dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install yt-dlp
        pip install python-telegram-bot --upgrade

    # 4. ุฅูุดุงุก ููู cookies.txt ูู GitHub Secrets
    - name: Create cookies file
      run: |
        # ุฅูุดุงุก ูุฌูุฏ ุงูุชุญูููุงุช
        mkdir -p downloads
        
        # ุฅูุดุงุก ููู cookies.txt ูู ุงูุณุฑ
        echo '${{ secrets.COOKIES_FILE }}' > cookies.txt
        
        # ุงูุชุญูู ูู ุฃู ุงูููู ุชู ุฅูุดุงุคู ุจุดูู ุตุญูุญ
        if [ -s "cookies.txt" ]; then
          echo "โ ุชู ุฅูุดุงุก cookies.txt ุจูุฌุงุญ"
          echo "ุญุฌู ุงูููู: $(wc -l < cookies.txt) ุณุทุฑ"
          head -2 cookies.txt  # ุนุฑุถ ุฃูู ุณุทุฑูู ููุชุญูู
        else
          echo "โ ุชุญุฐูุฑ: ููู cookies.txt ูุงุฑุบ ุฃู ุบูุฑ ููุฌูุฏ"
          # ุฅูุดุงุก ููู ูุงุฑุบ ูุชุฌูุจ ุงูุฃุฎุทุงุก
          touch cookies.txt
        fi

    # 5. ุชุดุบูู ุงูุจูุช
    - name: Run the bot
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}  # ุชููู ุงูุจูุช ูู Secrets
      run: |
        echo "๐ ุจุฏุก ุชุดุบูู ุงูุจูุช..."
        python bot.py

    # 6. ุชูุธูู ุงููููุงุช ุงููุคูุชุฉ (ุงุฎุชูุงุฑู)
    - name: Cleanup temporary files
      if: always()  # ูุนูู ุญุชู ูู ูุดูุช ุงูุฎุทูุฉ ุงูุณุงุจูุฉ
      run: |
        echo "๐งน ุชูุธูู ุงููููุงุช ุงููุคูุชุฉ..."
        rm -f cookies.txt
        rm -rf downloads/*
        echo "ุชู ุงูุชูุธูู"
